"""Fix tag model

Revision ID: 11233f37529b
Revises: 82a0dd710181
Create Date: 2024-01-14 14:47:55.515489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11233f37529b'
down_revision = '82a0dd710181'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
