"""Fix tag model

Revision ID: 2c2756c12daf
Revises: d7c077fb2185
Create Date: 2024-01-14 15:14:06.911926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c2756c12daf'
down_revision = 'd7c077fb2185'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
