"""Fix tag model

Revision ID: 82a0dd710181
Revises: 8da4063cec71
Create Date: 2024-01-14 14:47:08.637223

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82a0dd710181'
down_revision = '8da4063cec71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
