"""add enter and entry tags

Revision ID: b478a222b67f
Revises: 2c2756c12daf
Create Date: 2024-01-14 18:45:35.384519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b478a222b67f'
down_revision = '2c2756c12daf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
