"""Fix tag model

Revision ID: c15f38c1560a
Revises: 11233f37529b
Create Date: 2024-01-14 15:01:32.596356

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c15f38c1560a'
down_revision = '11233f37529b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tag', sa.Column('type', sa.Enum('place', 'person', 'activity', 'other', name='tagtype'), nullable=True))
    op.drop_column('tag', 'value')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tag', sa.Column('value', postgresql.ENUM('place', 'person', 'activity', 'other', name='tagtype'), autoincrement=False, nullable=True))
    op.drop_column('tag', 'type')
    # ### end Alembic commands ###
