"""add enter and entry tags

Revision ID: c9fc5aecd081
Revises: ff93300b3cc4
Create Date: 2024-01-14 18:55:07.959263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9fc5aecd081'
down_revision = 'ff93300b3cc4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
