"""Fix tag model

Revision ID: d7c077fb2185
Revises: c15f38c1560a
Create Date: 2024-01-14 15:03:06.168508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7c077fb2185'
down_revision = 'c15f38c1560a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
