"""add enter and entry tags

Revision ID: 10b5d8388d13
Revises: 1132aacaf6d0
Create Date: 2024-01-14 21:49:57.411261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10b5d8388d13'
down_revision = '1132aacaf6d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
