"""add enter and entry tags

Revision ID: 1132aacaf6d0
Revises: f71623c8d5f4
Create Date: 2024-01-14 21:48:01.380612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1132aacaf6d0'
down_revision = 'f71623c8d5f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
