"""Add date to entry

Revision ID: 7a8a0ddd3909
Revises: d29120518d0b
Create Date: 2024-01-29 20:58:03.478845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a8a0ddd3909'
down_revision = 'd29120518d0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entry', sa.Column('date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entry', 'date')
    # ### end Alembic commands ###
