"""remove date as the primary key in entry

Revision ID: ea38514a730d
Revises: 721f38665916
Create Date: 2024-01-29 21:13:11.332127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea38514a730d'
down_revision = '721f38665916'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
